### ISSUE TITLE
Mislabeled diagram

### ISSUE THREAD

**Issue by danhales** [learn-co-curriculum/dsc-dealing-missing-data#2]
The x-axis of the diagram illustrating standard deviations on the normal curve is labeled incorrectly. 

The labels are currently: μ-σ, μ-σ, μ-σ, 0, μ+σ, μ+σ, μ+σ

The labels should be: μ-3σ, μ-2σ, μ-σ, 0, μ+σ, μ+2σ, μ+3σ

Thank you!

**Comment by bpurdy-ds** [comment]
Corrected.
