### ISSUE TITLE
Small typo in subtitle

### ISSUE THREAD

**Issue by Juicob** [learn-co-curriculum/dsc-dealing-missing-data#3]
First time logging an issue so I hope this is the right place for this! 

I just noticed a [minor typo](https://i.imgur.com/7URYSV6.png) in one of the subheadings in the article. 

"Number of NaNs [[the in]] Titanic dataset by column"

I may try to follow the guidelines and attempt to fix the issue on my own after reading through!

**Comment by bpurdy-ds** [comment]
Corrected.
