### ISSUE TITLE
The figure showing standard deviation seems to have a typo

### ISSUE THREAD

**Issue by setare92-ha** [learn-co-curriculum/dsc-dealing-missing-data#5]
## Link to Canvas

https://learning.flatironschool.com/courses/7296/pages/dealing-with-missing-data?module_item_id=651197

## Issue Subtype

- [x ] Master branch code
- [ ] Solution branch code
- [ ] Code tests
- [ ] Layout/rendering issue
- [ ] Instructions unclear
- [ ] Other (explain below)

### Source

```
![image](https://github.com/learn-co-curriculum/dsc-dealing-missing-data/assets/152051671/0de5b880-55f0-4103-bec9-14dbc1b26d29)

```

### Concern

The grey text should read (\mu-3\sigma to \mu+3\sigma) but it currently reads (\mu-\sigma to \mu+\sigma)

## What OS Are You Using?

- [ ] OS X
- [ ] Windows
- [ ] WSL
- [ ] Linux
- [ ] Saturn Cloud from Canvas

**Comment by bpurdy-ds** [comment]
Thank you for letting us know about this one too. We'll take a look.

**Comment by bpurdy-ds** [comment]
Yes, you are correct.

**Comment by bpurdy-ds** [comment]
Fixed. Thank you again for noticing.
